name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_BE }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
          sudo docker stop backend || true
          sudo docker rm backend || true
          sudo docker run -d --name backend -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/backend:latest
